# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jflorentinbooking

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a42501ce93f741b5b7ee1dc6674f3c53 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_747ea7a5c9ee4d50909571ec7e3235fb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a42501ce93f741b5b7ee1dc6674f3c53 }}/twgroup.booking:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jflorentinbooking'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_64a11680372a4d99ac8bb4fae6f7aac1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a42501ce93f741b5b7ee1dc6674f3c53 }}/twgroup.booking:${{ github.sha }}'